// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAtjZGYA1rC9OFWFlxCelMZdwb-xfhqQ8',
    appId: '1:402374246370:web:40290755f32bd1322103bb',
    messagingSenderId: '402374246370',
    projectId: 'unawa-43922',
    authDomain: 'unawa-43922.firebaseapp.com',
    storageBucket: 'unawa-43922.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3qoy7e-QIyCszEK7ZzKyaQQ-SzvbvI3A',
    appId: '1:402374246370:android:28f4209e312ac5d82103bb',
    messagingSenderId: '402374246370',
    projectId: 'unawa-43922',
    storageBucket: 'unawa-43922.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABX3s_2HpXtyN4-KLDjZNV4bT6ZkG6pEs',
    appId: '1:402374246370:ios:e1c3d7c2fdd66e792103bb',
    messagingSenderId: '402374246370',
    projectId: 'unawa-43922',
    storageBucket: 'unawa-43922.appspot.com',
    iosClientId: '402374246370-gk37e1r3ahaof0ffrqmhoetqljvla1ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.signUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABX3s_2HpXtyN4-KLDjZNV4bT6ZkG6pEs',
    appId: '1:402374246370:ios:e1c3d7c2fdd66e792103bb',
    messagingSenderId: '402374246370',
    projectId: 'unawa-43922',
    storageBucket: 'unawa-43922.appspot.com',
    iosClientId: '402374246370-gk37e1r3ahaof0ffrqmhoetqljvla1ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.signUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAtjZGYA1rC9OFWFlxCelMZdwb-xfhqQ8',
    appId: '1:402374246370:web:23422e8e7485dd1f2103bb',
    messagingSenderId: '402374246370',
    projectId: 'unawa-43922',
    authDomain: 'unawa-43922.firebaseapp.com',
    storageBucket: 'unawa-43922.appspot.com',
  );

}